M48
; DRILL file {KiCad (6.0.1-0)} date Sunday, 10 July 2022 at 21:45:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-10T21:45:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X147.11Y-75.6
X152.89Y-75.6
T2
X124.0Y-77.0
X124.0Y-123.0
X176.0Y-77.0
X176.0Y-123.0
T0
M30
